# Generated by Django 2.2 on 2019-04-24 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190423_2057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
