# Generated by Django 2.2 on 2019-04-24 15:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular test registration', primary_key=True, serialize=False)),
                ('student_first', models.CharField(max_length=100)),
                ('student_last', models.CharField(max_length=100)),
                ('year_in_school', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FR', max_length=2)),
                ('substitute', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('Time_Slot_0930', models.ManyToManyField(help_text='Select a genre for this book', to='catalog.Exam')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.School')),
            ],
            options={
                'ordering': ['school'],
            },
        ),
    ]
