# Generated by Django 2.2 on 2019-04-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_testschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testschedule',
            name='substitute',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
    ]
