# Generated by Django 2.2 on 2019-04-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190424_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testschedule',
            name='Time_Slot_0930',
            field=models.ManyToManyField(help_text='Select an exam.', to='catalog.Exam'),
        ),
    ]
