# Generated by Django 2.2 on 2019-04-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20190424_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testschedule',
            options={'ordering': ['student_last']},
        ),
        migrations.RenameField(
            model_name='testschedule',
            old_name='Time_Slot_0930',
            new_name='Time_1',
        ),
        migrations.RemoveField(
            model_name='testschedule',
            name='school',
        ),
        migrations.AddField(
            model_name='testschedule',
            name='school',
            field=models.ManyToManyField(help_text='Select a school', to='catalog.School'),
        ),
    ]
