# Generated by Django 2.2 on 2019-04-25 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20190425_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testschedule',
            name='Time_1',
        ),
    ]
