# Generated by Django 2.2 on 2019-05-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_testschedule_time_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='testschedule',
            name='Time_1',
            field=models.CharField(choices=[('No', '-------'), ('Accounting', 'Accounting'), ('Agriculture Business', 'Agriculture Business'), ('Algebra I', 'Algebra I'), ('Algebra II', 'Algebra II'), ('American Government', 'American Government'), ('American History', 'American History'), ('American Literature', 'American Literature'), ('Anatomy and Physiology', 'Anatomy and Physiology'), ('Art Drawing', 'Art Drawing'), ('Art Portfolio', 'Art Portfolio'), ('Behavioral Science', 'Behavioral Science')], default='No', max_length=30),
        ),
        migrations.AddField(
            model_name='testschedule',
            name='Time_2',
            field=models.CharField(choices=[('No', '-------'), ('Accounting', 'Accounting'), ('Agriculture Business', 'Agriculture Business'), ('Algebra I', 'Algebra I'), ('Algebra II', 'Algebra II'), ('American Government', 'American Government'), ('American History', 'American History'), ('American Literature', 'American Literature'), ('Anatomy and Physiology', 'Anatomy and Physiology'), ('Art Drawing', 'Art Drawing'), ('Art Portfolio', 'Art Portfolio'), ('Behavioral Science', 'Behavioral Science')], default='No', max_length=30),
        ),
        migrations.AddField(
            model_name='testschedule',
            name='Time_3',
            field=models.CharField(choices=[('No', '-------'), ('Accounting', 'Accounting'), ('Agriculture Business', 'Agriculture Business'), ('Algebra I', 'Algebra I'), ('Algebra II', 'Algebra II'), ('American Government', 'American Government'), ('American History', 'American History'), ('American Literature', 'American Literature'), ('Anatomy and Physiology', 'Anatomy and Physiology'), ('Art Drawing', 'Art Drawing'), ('Art Portfolio', 'Art Portfolio'), ('Behavioral Science', 'Behavioral Science')], default='No', max_length=30),
        ),
    ]
