# Generated by Django 2.2 on 2019-05-01 12:34

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20190430_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='state',
            field=localflavor.us.models.USStateField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='testschedule',
            name='Time_1',
            field=models.CharField(choices=[('No', '-------'), ('Accounting', 'Accounting'), ('Agriculture Business', 'Agriculture Business'), ('Algebra I', 'Algebra I'), ('Algebra II', 'Algebra II'), ('American Government', 'American Government'), ('American History', 'American History'), ('American Literature', 'American Literature'), ('Anatomy and Physiology', 'Anatomy and Physiology'), ('Art Drawing', 'Art Drawing'), ('Art Portfolio', 'Art Portfolio'), ('Behavioral Science', 'Behavioral Science'), ('Business Math', 'Business Math'), ('Calculus', 'Calculus'), ('Chemistry', 'Chemistry'), ('Child Development', 'Child Development'), ('Computer Fundamentals', 'Computer Fundamentals'), ('Current Events', 'Current Events'), ('English Literature', 'English Literature'), ('Expository Writing (Div I and Div II)', 'Expository Writing (Div I and Div II)'), ('Expository Writing (Div III and Div IV)', 'Expository Writing (Div III and Div IV)'), ('General Biology', 'General Biology'), ('General Science', 'General Science'), ('Geometry', 'Geometry'), ('Library Skills', 'Library Skills'), ('Music', 'Music'), ('Oklahoma History', 'Oklahoma History'), ('Oklahoma Wildlife Identification', 'Oklahoma Wildlife Identification'), ('Physics', 'Physics'), ('PowerPoint Presentation (Div I and Div II)', 'PowerPoint Presentation (Div I and Div II)'), ('PowerPoint Presentation (Div III and Div IV)', 'PowerPoint Presentation (Div III and Div IV)'), ('Spanish', 'Spanish'), ('Spreadsheet Applications', 'Spreadsheet Applications'), ('Trigonometry', 'Trigonometry'), ('Vocabulary', 'Vocabulary'), ('World Geography', 'World Geography'), ('World History', 'World History')], default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='testschedule',
            name='Time_2',
            field=models.CharField(choices=[('No', '-------'), ('Accounting', 'Accounting'), ('Agriculture Business', 'Agriculture Business'), ('Algebra I', 'Algebra I'), ('Algebra II', 'Algebra II'), ('American Government', 'American Government'), ('American History', 'American History'), ('American Literature', 'American Literature'), ('Anatomy and Physiology', 'Anatomy and Physiology'), ('Art Drawing', 'Art Drawing'), ('Art Portfolio', 'Art Portfolio'), ('Behavioral Science', 'Behavioral Science'), ('Business Math', 'Business Math'), ('Calculus', 'Calculus'), ('Chemistry', 'Chemistry'), ('Child Development', 'Child Development'), ('Computer Fundamentals', 'Computer Fundamentals'), ('Current Events', 'Current Events'), ('English Literature', 'English Literature'), ('Expository Writing (Div I and Div II)', 'Expository Writing (Div I and Div II)'), ('Expository Writing (Div III and Div IV)', 'Expository Writing (Div III and Div IV)'), ('General Biology', 'General Biology'), ('General Science', 'General Science'), ('Geometry', 'Geometry'), ('Library Skills', 'Library Skills'), ('Music', 'Music'), ('Oklahoma History', 'Oklahoma History'), ('Oklahoma Wildlife Identification', 'Oklahoma Wildlife Identification'), ('Physics', 'Physics'), ('PowerPoint Presentation (Div I and Div II)', 'PowerPoint Presentation (Div I and Div II)'), ('PowerPoint Presentation (Div III and Div IV)', 'PowerPoint Presentation (Div III and Div IV)'), ('Spanish', 'Spanish'), ('Spreadsheet Applications', 'Spreadsheet Applications'), ('Trigonometry', 'Trigonometry'), ('Vocabulary', 'Vocabulary'), ('World Geography', 'World Geography'), ('World History', 'World History')], default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='testschedule',
            name='Time_3',
            field=models.CharField(choices=[('No', '-------'), ('Accounting', 'Accounting'), ('Agriculture Business', 'Agriculture Business'), ('Algebra I', 'Algebra I'), ('Algebra II', 'Algebra II'), ('American Government', 'American Government'), ('American History', 'American History'), ('American Literature', 'American Literature'), ('Anatomy and Physiology', 'Anatomy and Physiology'), ('Art Drawing', 'Art Drawing'), ('Art Portfolio', 'Art Portfolio'), ('Behavioral Science', 'Behavioral Science'), ('Business Math', 'Business Math'), ('Calculus', 'Calculus'), ('Chemistry', 'Chemistry'), ('Child Development', 'Child Development'), ('Computer Fundamentals', 'Computer Fundamentals'), ('Current Events', 'Current Events'), ('English Literature', 'English Literature'), ('Expository Writing (Div I and Div II)', 'Expository Writing (Div I and Div II)'), ('Expository Writing (Div III and Div IV)', 'Expository Writing (Div III and Div IV)'), ('General Biology', 'General Biology'), ('General Science', 'General Science'), ('Geometry', 'Geometry'), ('Library Skills', 'Library Skills'), ('Music', 'Music'), ('Oklahoma History', 'Oklahoma History'), ('Oklahoma Wildlife Identification', 'Oklahoma Wildlife Identification'), ('Physics', 'Physics'), ('PowerPoint Presentation (Div I and Div II)', 'PowerPoint Presentation (Div I and Div II)'), ('PowerPoint Presentation (Div III and Div IV)', 'PowerPoint Presentation (Div III and Div IV)'), ('Spanish', 'Spanish'), ('Spreadsheet Applications', 'Spreadsheet Applications'), ('Trigonometry', 'Trigonometry'), ('Vocabulary', 'Vocabulary'), ('World Geography', 'World Geography'), ('World History', 'World History')], default='No', max_length=30),
        ),
    ]
