# Generated by Django 2.2 on 2019-05-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20190501_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='division',
            field=models.CharField(choices=[('-', '-'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='-', max_length=1),
        ),
        migrations.AlterField(
            model_name='school',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
