# Generated by Django 2.2 on 2019-05-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20190501_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testschedule',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
